name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}-lint
  cancel-in-progress: true

jobs:
  lint:
    name: Go Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Golang Environment
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Lint Go
        uses: golangci/golangci-lint-action@v8

  actionlint:
    name: Actionlint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Lint Actions
        uses: reviewdog/action-actionlint@v1
        with:
          actionlint_flags: -shellcheck ""
